services:
  server:
    container_name: schedule-viewer-server
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./files:/server/files 
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGODB_URI=mongodb://database:27017/schedule-viewer

  database:
    image: mongo:latest
    container_name: schedule-viewer-db
    environment:
      - MONGO_INITDB_DATABASE=schedule-viewer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
