version: "3"

services:
  server:
    container_name: server
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - custom_network
    depends_on:
      - database

  database:
    container_name: database
    image: mongo:latest
    restart: always
    environment:
      POSTGRES_DB: schedule-viewer
    ports:
      - "27017:27017"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    name: custom_network
